// check out https://github.com/visionmedia/node-pwd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
var crypto = require('crypto'); 


var db = require("./db")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
/**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 * Bytesize.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
 */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
var len = 32;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
/**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 * Iterations. ~300ms                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
 */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
var iterations = 1000;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
/**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 * Hashes a password with optional `salt`, otherwise                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
 * generate a salt for `pass` and invoke `fn(err, salt, hash)`.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
 *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 * @param {String} password to hash                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
 * @param {String} optional salt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 * @param {Function} callback                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
 * @api public                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

exports.hash_login = function (pwd, salt, fn) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    return crypto.pbkdf2(pwd, salt, iterations, len,"sha1", fn);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
};

exports.hash_register = function (name,doj, email, address, contact, centre, subject, userid, pwd, next) {   
	console.log("ho ho");	
		console.log(name, doj, email, address, contact, centre,subject, userid, pwd);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    crypto.randomBytes(len, function(err, salt){                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      if (err)
      { return next(err);}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
      var v_salt = salt.toString('hex');      
      console.log(salt); 
      crypto.pbkdf2(pwd , v_salt , iterations, len,"sha1",function(err, hash){
      console.log(hash.toString("hex"));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        if (err) return next(err);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        var v_hash = hash.toString("hex");
      // db.getConnection(function(err, conn){
      if (err)
      {
        console.error('SQL Connection error: ',err);
        return next(err);
      }
      else
      {        
      	// console.log("even here");
      	console.log(v_hash,v_salt);
      	console.log('insert into volunteer_info (v_name,v_username,centre,v_salt,v_hash,email,v_doj,subject,address,contact) values("' + name + '","' + userid + '","' + centre + '","' + v_salt + '","' + v_hash + '","' + email + '","' + doj + '","' + subject + '","' + address + '","' + contact + '");');
        db.query('insert into volunteer_info (v_name,v_username,centre,v_salt,v_hash,email,v_doj,subject,address,contact) values("' + name + '","' + userid + '","' + centre + '","' + v_salt + '","' + v_hash + '","' + email + '","' + doj + '","' + subject + '","' + address + '","' + contact + '");', function(err, rows, fields){
 
          console.log("values updated");
          return next();
          });
        
      }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  });                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
});
}